BallHogs/BallHogs/Controllers/BHTeamsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BallHogs.Models;
using Microsoft.AspNetCore.Http;
using System.Net.Http;

namespace BallHogs.Controllers
{
    public class BHTeamsController : Controller
    {
        private readonly IHttpClientFactory _httpClientFactory;
        private readonly DataContext _context;
        private readonly ISession _session;

        public BHTeamsController(IHttpClientFactory httpClientFactory, DataContext context, IHttpContextAccessor httpContextAccessor)
        {
            _httpClientFactory = httpClientFactory;
            _context = context;
            _session = httpContextAccessor.HttpContext.Session;
        }

        // GET: BHTeams
        public async Task<IActionResult> Index()
        {
            ViewBag.UID = User.Identity.Name;
            return View(await _context.BHTeams.Where(m => m.ManagerName == User.Identity.Name).ToListAsync());
        }

        //Attempt to bring team to LETS BALL!!!
        public async Task<IActionResult> SelectATeam()
        {
            return View(await _context.BHTeams.ToListAsync());
        }

        // GET: BHTeams/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vm = new DataVM();

            vm.BHTeam = await _context.BHTeams.FirstOrDefaultAsync(m => m.BHTeamId == id);
            if (vm.BHTeam == null)
            {
                return NotFound();
            }
            vm.Players = await _context.PlayersOnTeams.Where(x => x.BHTeamId == id).ToListAsync();

            _session.SetInt32("Team", vm.BHTeam.BHTeamId);
            return View(vm);
        }

        // GET: BHTeams/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: BHTeams/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("BHTeamId,TeamName")] BHTeam bHTeam)
        {
            bHTeam.ManagerName = User.Identity.Name;
            if (ModelState.IsValid)
            {
                _context.Add(bHTeam);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(bHTeam);
        }

        // GET: BHTeams/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bHTeam = await _context.BHTeams.FindAsync(id);
            if (bHTeam == null)
            {
                return NotFound();
            }
            return View(bHTeam);
        }

        // POST: BHTeams/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("BHTeamId,TeamName,ManagerName")] BHTeam bHTeam)
        {
            if (id != bHTeam.BHTeamId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(bHTeam);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BHTeamExists(bHTeam.BHTeamId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(bHTeam);
        }

        // GET: BHTeams/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bHTeam = await _context.BHTeams
                .FirstOrDefaultAsync(m => m.BHTeamId == id);
            if (bHTeam == null)
            {
                return NotFound();
            }

            return View(bHTeam);
        }

        // POST: BHTeams/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var bHTeam = await _context.BHTeams.FindAsync(id);
            _context.BHTeams.Remove(bHTeam);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BHTeamExists(int id)
        {
            return _context.BHTeams.Any(e => e.BHTeamId == id);
        }
    }
}

BallHogs/BallHogs/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using BallHogs.Models;
using System.Net.Http;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;

namespace BallHogs.Controllers
{
    public class HomeController : Controller
    {
        private readonly IHttpClientFactory _httpClientFactory;
        private readonly DataContext _context;
        private readonly ISession _session;



        public HomeController(IHttpClientFactory httpClientFactory, DataContext context, IHttpContextAccessor httpContextAccessor)
        {
            _httpClientFactory = httpClientFactory;
            _context = context;
            _session = httpContextAccessor.HttpContext.Session;
        }

        public async Task<IActionResult> Index()
        {
            ViewBag.LoggedIn = User.Identity.IsAuthenticated;
            ViewBag.UID = User.Identity.Name;

            if (User.Identity.IsAuthenticated)
            {
                var manager = await _context.Managers.FirstOrDefaultAsync(m => m.UserName == User.Identity.Name);
                if(manager == null)
                {
                    manager = new Manager(User.Identity.Name);
                    _context.Add(manager);
                    await _context.SaveChangesAsync();
                }
            }
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Index(string player)
        {
            var client = _httpClientFactory.CreateClient();
            client.BaseAddress = new Uri("https://www.balldontlie.io");

            var response = await client.GetAsync($"/api/v1/players?search={player}");

            var body = await response.Content.ReadAsStringAsync();

            var content = JsonConvert.DeserializeObject<ApiModel>(body);
            var playersWithPosition = content.Data.Where(x => !string.IsNullOrEmpty(x.Position)).ToArray();
            content.Data = playersWithPosition;

            return View("SearchResult", content);
        }
        
        public async Task<IActionResult> LetsBall()
        {
            ViewBag.UID = User.Identity.Name;

            var allTeams = await _context.BHTeams.ToListAsync();
            var fullTeams = new List<BHTeam>();
            foreach(var team in allTeams)
            {
                var allPlayers = await _context.PlayersOnTeams.Where(m => m.BHTeamId == team.BHTeamId).ToListAsync();
                if (allPlayers.Count == 5) fullTeams.Add(team);
            }
            return View(fullTeams);
        }

        [HttpPost]
        public async Task<IActionResult> LetsBall(int homeId, int awayId, int? games)
        {
            var home = await _context.BHTeams.FirstOrDefaultAsync(m => m.BHTeamId == homeId);
            var away = await _context.BHTeams.FirstOrDefaultAsync(m => m.BHTeamId == awayId);

            var homePlayers = await _context.PlayersOnTeams.Where(m => m.BHTeamId == homeId).ToListAsync();
            var awayPlayers = await _context.PlayersOnTeams.Where(m => m.BHTeamId == awayId).ToListAsync();

            foreach(var player in homePlayers)
            {
                home.Players.Add(player);
            }
            foreach(var player in awayPlayers)
            {
                away.Players.Add(player);
            }

            var series = new Series(home, away, games);
            return View("Results", series);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BallHogs/BallHogs/Views/Home/Index.cshtml
@model ApiModel
@{
    ViewData["Title"] = "Home Page";
}    

<div class="text-center">
    @if (ViewBag.LoggedIn)
    {
        <p>Hello, @ViewBag.UID</p>
        <div align="center">
            <a asp-controller="BHTeams" asp-action="Create">Create a BallHog Team</a>
        </div>
        <div class="text-center">
            @if (ViewBag.LoggedIn)
            {
                <p>Hello, @ViewBag.UID</p>
                <div align="center">
                    <a asp-controller="BHTeams" asp-action="Create">Create a BallHog Team</a>
                </div>
                <div align="center">
                    <a asp-controller="BHTeams" asp-action="Index">Manage My BallHog Team</a>
                </div>
                <div align="center">
                    <a asp-controller="Home" asp-action="LetsBall">LETS BALL!!!</a>
                </div>
            }
            else
            {
                <p>Please <a asp-area="Identity" asp-page="/Account/Login">Login</a> or <a asp-area="Identity" asp-page="/Account/Register">Register</a></p>
            }
            <br />
            <br />
        </div>

BallHogs/BallHogs/Views/Home/LetsBall.cshtml
@model List<BHTeam>

@{
    ViewData["Title"] = "LetsBall";
}

<h1>LetsBall</h1>

<form asp-controller="Home" asp-action="LetsBall" method="post">

    <h2>Home</h2>
    <p>
        <div>
            Please choose a home team: 
        </div>
        @foreach (var team in Model)
        {
            @if (team.ManagerName == ViewBag.UID)
            {
                <input type="radio" checked="checked" name="homeId" value="@team.BHTeamId">@team.TeamName<br>
            }
        }
    </p>
    <h2>Away</h2>
    <p>
        <div>
            Please choose an away team:
        </div>
        @foreach (var team in Model)
        {
            @if (team.ManagerName != ViewBag.UID)
            {
                <input type="radio" checked="checked" name="awayId" value="@team.BHTeamId">@team.TeamName<br>
            }
        }
    </p>
    <p>
        <div>
            Please select game/series:
        </div>
        <input type="radio" checked="checked" name="games" value="1"> Play 1 Game<br>
        <input type="radio" name="games" value="3"> Play 3-Game Series<br>
        <input type="radio" name="games" value="5"> Play 5-Game Series<br>
        <input type="radio" name="games" value="7"> Play 7-Game Series<br>
        <input type="radio" name="games" value="null"> Play Until Both Teams Win<br>
    </p>

    <input type="submit" value="Lets Ball!" />

</form>

BallHogs/BallHogs/Views/Home/Results.cshtml
@model Series
@{
    ViewData["Title"] = "Results";
}

<h1>Results</h1>

<h1>@Model.Winner.TeamName Wins in @Model.GamesPlayed</h1>

<h2>Home: @Model.HomeTeam.TeamName vs Away: @Model.AwayTeam.TeamName</h2>
<h2>@Model.HomeWins - @Model.AwayWins</h2>

<h2>Scores:</h2>
@foreach(var game in Model.SeriesResult)
{
    <h3>Game @game.GameNum:  @game.HomeScore - @game.AwayScore</h3>
}

BallHogs/BallHogs/Views/Home/SearchPlayer.cshtml
@{
    ViewData["Title"] = "SearchPlayer";
}

<h1>Search NBA Players</h1>

<form asp-controller="Home" asp-action="Index" method="post">
    <p>
        Player Search: <input type="text" name="player" />
        <input type="submit" value="Search" />
    </p>
</form>

BallHogs/BallHogs/Views/Home/SearchResult.cshtml
@model ApiModel
@{
    ViewData["Title"] = "SearchResult";
}

<h1>Search other NBA Players</h1>

<form asp-controller="Home" asp-action="Index" method="post">
    <p>
        Player Search: <input type="text" name="player" />
        <input type="submit" value="Search" />
    </p>
</form>

<h2>List of Players</h2>
<table class="table">

    <tbody>
        @foreach (var item in Model.Data)
        {
            <tr style="color:white">
                <td align="left">
                    @Html.DisplayFor(modelItem => item.First_name)
                </td>
                <td align="left">
                    @Html.DisplayFor(modelItem => item.Last_name)
                </td>
                <td align="left">
                    @Html.DisplayFor(modelItem => item.Position)
                </td>
                <td align="left">
                    @using (Html.BeginForm("Create", "PlayersOnTeam", new { FirstName = item.First_name, LastName = item.Last_name, Position = item.Position, link = item.Id }))
                    {
                        <input class="button" type="submit" value="Add to player to team" />
                    }
                </td>
            </tr>
        }
    </tbody>
</table>