BallHogs/BallHogs/Models/BHTeam.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BallHogs.Models
{
    public class BHTeam
    {
        public int BHTeamId { get; set; }
        public string TeamName { get; set; }
        public string ManagerName { get; set; }

        public ICollection<Datum> Players { get; set; }
    }
}

BallHogs/BallHogs/Controllers/BHTeamsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BallHogs.Models;
using Microsoft.AspNetCore.Http;
using System.Net.Http;

namespace BallHogs.Controllers
{
    public class BHTeamsController : Controller
    {
        private readonly IHttpClientFactory _httpClientFactory;
        private readonly DataContext _context;
        private readonly ISession _session;

        public BHTeamsController(IHttpClientFactory httpClientFactory, DataContext context, IHttpContextAccessor httpContextAccessor)
        {
            _httpClientFactory = httpClientFactory;
            _context = context;
            _session = httpContextAccessor.HttpContext.Session;
        }

        // GET: BHTeams
        public async Task<IActionResult> Index()
        {
            ViewBag.UID = User.Identity.Name;
            return View(await _context.BHTeams.Where(m => m.ManagerName == User.Identity.Name).ToListAsync());
        }

        //Attempt to bring team to LETS BALL!!!
        public async Task<IActionResult> SelectATeam()
        {
            return View(await _context.BHTeams.ToListAsync());
        }

        // GET: BHTeams/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vm = new DataVM();

            vm.BHTeam = await _context.BHTeams.FirstOrDefaultAsync(m => m.BHTeamId == id);
            if (vm.BHTeam == null)
            {
                return NotFound();
            }
            vm.Players = await _context.PlayersOnTeams.Where(x => x.BHTeamId == id).ToListAsync();

            _session.SetInt32("Team", vm.BHTeam.BHTeamId);
            return View(vm);
        }

        // GET: BHTeams/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: BHTeams/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("BHTeamId,TeamName")] BHTeam bHTeam)
        {
            bHTeam.ManagerName = User.Identity.Name;
            if (ModelState.IsValid)
            {
                _context.Add(bHTeam);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(bHTeam);
        }

        // GET: BHTeams/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bHTeam = await _context.BHTeams.FindAsync(id);
            if (bHTeam == null)
            {
                return NotFound();
            }
            return View(bHTeam);
        }

        // POST: BHTeams/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("BHTeamId,TeamName,ManagerName")] BHTeam bHTeam)
        {
            if (id != bHTeam.BHTeamId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(bHTeam);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BHTeamExists(bHTeam.BHTeamId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(bHTeam);
        }

        // GET: BHTeams/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bHTeam = await _context.BHTeams
                .FirstOrDefaultAsync(m => m.BHTeamId == id);
            if (bHTeam == null)
            {
                return NotFound();
            }

            return View(bHTeam);
        }

        // POST: BHTeams/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var bHTeam = await _context.BHTeams.FindAsync(id);
            _context.BHTeams.Remove(bHTeam);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BHTeamExists(int id)
        {
            return _context.BHTeams.Any(e => e.BHTeamId == id);
        }
    }
}

BallHogs/BallHogs/Controllers/PlayersOnTeamsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BallHogs.Models;
using System.Net.Http;
using Microsoft.AspNetCore.Http;
using Newtonsoft.Json;

namespace BallHogs.Controllers
{
    public class PlayersOnTeamsController : Controller
    {
        private readonly IHttpClientFactory _httpClientFactory;
        private readonly DataContext _context;
        private readonly ISession _session;

        public PlayersOnTeamsController(IHttpClientFactory httpClientFactory, DataContext context, IHttpContextAccessor httpContextAccessor)
        {
            _httpClientFactory = httpClientFactory;
            _context = context;
            _session = httpContextAccessor.HttpContext.Session;
        }


        // GET: PlayersOnTeams
        public async Task<IActionResult> Index()
        {
            var dataContext = _context.BHTeams.Include(r => r.Players).Where(x => x.ManagerName == User.Identity.Name);
            return View(await dataContext.ToListAsync());
        }

        [HttpPost]
        public async Task<IActionResult> SearchGuards(string player)
        {
            var client = _httpClientFactory.CreateClient();
            client.BaseAddress = new Uri("https://www.balldontlie.io");

            var response = await client.GetAsync($"/api/v1/players?search={player}");

            var body = await response.Content.ReadAsStringAsync();

            var content = JsonConvert.DeserializeObject<ApiModel>(body);

            var playersWithPosition = content.Data.Where(x => !string.IsNullOrEmpty(x.Position) && x.Position == "G" || x.Position == "G-F").ToArray();

            content.Data = playersWithPosition;

            return View("SearchResult", content);
        }

        [HttpPost]
        public async Task<IActionResult> SearchForwards(string player)
        {
            var client = _httpClientFactory.CreateClient();
            client.BaseAddress = new Uri("https://www.balldontlie.io");

            var response = await client.GetAsync($"/api/v1/players?search={player}");

            var body = await response.Content.ReadAsStringAsync();

            var content = JsonConvert.DeserializeObject<ApiModel>(body);

            var playersWithPosition = content.Data.Where(x => !string.IsNullOrEmpty(x.Position) && x.Position == "F").ToArray();
            content.Data = playersWithPosition;

            return View("SearchResult", content);
        }

        [HttpPost]
        public async Task<IActionResult> SearchCenter(string player)
        {
            var client = _httpClientFactory.CreateClient();
            client.BaseAddress = new Uri("https://www.balldontlie.io");

            var response = await client.GetAsync($"/api/v1/players?search={player}");

            var body = await response.Content.ReadAsStringAsync();

            var content = JsonConvert.DeserializeObject<ApiModel>(body);

            var playersWithPosition = content.Data.Where(x => !string.IsNullOrEmpty(x.Position) && x.Position == "C" || x.Position == "F-C").ToArray();
            content.Data = playersWithPosition;

            return View("SearchResult", content);
        }

        [HttpPost]
        public async Task<IActionResult> SearchAll(string player, int year)
        {
            var client = _httpClientFactory.CreateClient();
            client.BaseAddress = new Uri("https://www.balldontlie.io");

            var response = await client.GetAsync($"/api/v1/players?search={player}");

            var body = await response.Content.ReadAsStringAsync();

            var content = JsonConvert.DeserializeObject<ApiModel>(body);

            year = 2018;
            var playersWithPosition = content.Data.Where(x => !string.IsNullOrEmpty(x.Position)).ToArray();
            content.Data = playersWithPosition;

            return View("SearchResult", content);
        }

        [HttpPost]
        public async Task<IActionResult> LegendarySearch(string player, int year)
        {
            var client = _httpClientFactory.CreateClient();
            client.BaseAddress = new Uri("https://www.balldontlie.io");

            var response = await client.GetAsync($"/api/v1/players?search={player}");

            var body = await response.Content.ReadAsStringAsync();

            var content = JsonConvert.DeserializeObject<ApiModel>(body);
            TempData["Year"] = year;

            if (year == 0)
            {
                return RedirectToAction("Index");
            }

            return View("SearchResult", content);
        }

        // GET: PlayersOnTeams/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var playersOnTeams = await _context.PlayersOnTeams
                .Include(p => p.BHTeam)
                .FirstOrDefaultAsync(m => m.PlayersOnTeamsId == id);
            if (playersOnTeams == null)
            {
                return NotFound();
            }

            return View(playersOnTeams);
        }

        // Needs more work should everything _context actually be stored in session?
        // https://www.balldontlie.io/api/v1/season_averages?player_ids[]=735&season=2000
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddPlayer(string first_name, string last_name, string position, int year, int id)
        {
            var teamID = _session.GetInt32("Team");
            var team = await _context.BHTeams.Include(x => x.Players).FirstOrDefaultAsync(m => m.BHTeamId == teamID);

            if (team.Players.Any(x => x.PlayerAPINum == id))
            {
                return RedirectToAction("Details", "BHTeams", new { id = teamID });
            }

            if (position == null || year < 2018 && year != 0)
            {

                var stats = await GetStats(id, year);
                if (stats == null) return RedirectToAction("Index"); // no stats!

                var playerOnTeam = new PlayersOnTeams
                {
                    BHTeamId = (int)teamID,
                    BHTeam = team,
                    PlayerAPINum = id,
                    Name = first_name + " " + last_name,
                    Position = position,
                    Year = year,
                    PPG = stats.pts,
                    Steals = stats.stl,
                    Rebounds = stats.reb
                };
                if (team.Players.Any(x => x.PlayerAPINum == id))
                {
                    return RedirectToAction("Details", "BHTeams", new { id = teamID });
                }
                _context.Add(playerOnTeam);
                await _context.SaveChangesAsync();
            }
            
            if (position != null && year == 2018 || year == 0)
            {
                if (User.Identity.IsAuthenticated && teamID != null)
                {
                    team = await _context.BHTeams.FirstOrDefaultAsync(m => m.BHTeamId == teamID);

                    year = 2018;

                    var stats = await GetStats(id, year);
                    if (stats == null) return RedirectToAction("Index"); // no stats!

                    var playerOnTeam = new PlayersOnTeams
                    {
                        BHTeamId = (int)teamID,
                        BHTeam = team,
                        PlayerAPINum = id,
                        Name = first_name + " " + last_name,
                        Position = position,
                        Year = year,
                        PPG = stats.pts,
                        Steals = stats.stl,
                        Rebounds = stats.reb
                    };

                    _context.Add(playerOnTeam);
                    await _context.SaveChangesAsync();
                    return RedirectToAction("Details", "BHTeams", new { id = teamID });
                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }
                
            }

            if (User.Identity.IsAuthenticated && teamID != null)
            {
                team = await _context.BHTeams.FirstOrDefaultAsync(m => m.BHTeamId == teamID);


                var stats = await GetStats(id, year);
                if (stats == null) return RedirectToAction("Index"); // no stats!

                var playerOnTeam = new PlayersOnTeams
                {
                    BHTeamId = (int)teamID,
                    BHTeam = team,
                    PlayerAPINum = id,
                    Name = first_name + " " + last_name,
                    Position = position,
                    Year = year,
                    PPG = stats.pts,
                    Steals = stats.stl,
                    Rebounds = stats.reb
                };

                return RedirectToAction("Details", "BHTeams", new { id = teamID });
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> RemovePlayer(int id)
        {
            var teamID = _session.GetInt32("Team");

            var player = await _context.PlayersOnTeams.FindAsync(id);
            _context.PlayersOnTeams.Remove(player);
            await _context.SaveChangesAsync();
            return RedirectToAction("Details", "BHTeams", new { id = teamID });
        }



        // GET: PlayersOnTeams/Create
        public IActionResult Create()
        {
            ViewData["BHTeamId"] = new SelectList(_context.BHTeams, "BHTeamId", "BHTeamId");
            return View();
        }

        // POST: PlayersOnTeams/Create

BallHogs/BallHogs/Views/BHTeams/Create.cshtml
@model BallHogs.Models.BHTeam

@{
    ViewData["Title"] = "Create";
}

    <div class="text-center">
        <h1>Create your BallHog Team</h1>

        <p>Please provide your team name to create a new Ballhog team</p>
    </div>

        <hr />
        <div class="row">
            <div class="col-md-4">
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="TeamName" class="control-label" value="Team Name"></label>
                        <input asp-for="TeamName" class="form-control" />
                        <span asp-validation-for="TeamName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Create" class="btn btn-primary" />
                    </div>
                </form>
            </div>
        </div>

        <div>
            <a asp-action="Index">Back to List</a>
        </div>

        @section Scripts {
            @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
        }

BallHogs/BallHogs/Views/BHTeams/Delete.cshtml
@model BallHogs.Models.BHTeam

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>BHTeam</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TeamName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TeamName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ManagerName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ManagerName)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="BHTeamId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

BallHogs/BallHogs/Views/BHTeams/Details.cshtml
@model BallHogs.Models.DataVM

@{
    ViewData["Title"] = "Details";
}

<h1>Manage your team</h1>

<div>
    <h4>BHTeam</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.BHTeam.TeamName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.BHTeam.TeamName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.BHTeam.ManagerName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.BHTeam.ManagerName)
        </dd>
    </dl>
    <h5>Players</h5>
    @if (Model.Players != null)
    {
        <dl class="row">
            @foreach (var player in Model.Players)
            {
                <dd class="col-sm-10">
                    @player.Name
                </dd>
                <dd class="col-sm-10">
                    @if (player.Year != 2018)
                    {
                        @player.Year
                    }
                    @player.Position
                </dd>
                <dd>
                    <form method="post">
                        <button type="submit" asp-controller="PlayersOnTeams" asp-action="RemovePlayer" asp-route-id="@player.PlayersOnTeamsId">Remove Player</button>
                    </form>
                </dd>
            }
        </dl>
    }
    <p>**Teams without 5 players cannot participate in LETS BALL games**</p>
    @if (Model.Players == null || Model.Players.Count < 5)
    {
        <div>
            <a asp-action="Index" asp-controller="PlayersOnTeams">Add a Player</a> |
        </div>
    }

</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.BHTeam.BHTeamId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

BallHogs/BallHogs/Views/BHTeams/Edit.cshtml
@model BallHogs.Models.BHTeam

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>BHTeam</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="BHTeamId" />
            <div class="form-group">
                <label asp-for="TeamName" class="control-label"></label>
                <input asp-for="TeamName" class="form-control" />
                <span asp-validation-for="TeamName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ManagerName" class="control-label"></label>
                <input asp-for="ManagerName" class="form-control" />
                <span asp-validation-for="ManagerName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BallHogs/BallHogs/Views/BHTeams/Index.cshtml
@model IEnumerable<BallHogs.Models.BHTeam>

@{
    ViewData["Title"] = "Index";
}

<h1>BHTeams</h1>

<p>
    <a asp-action="Create">Create a New BHTeam</a>
</p>
<p>
    Please manage your BallHog team to ensure your team has 5 players
    <br />
    **Teams without 5 players cannot participate in LETS BALL games**
</p>

<table class="table">
    <thead>
        <tr style="color:white">
            <th>
                Team Name
            </th>
            <th>
                Manager Name
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td style="color:white">
                @Html.DisplayFor(modelItem => item.TeamName)
            </td>
            <td style="color:white">
                @Html.DisplayFor(modelItem => item.ManagerName)
            </td>
            @if (item.ManagerName == ViewBag.UID)
            {
                <td style="color:white">
                    <a asp-action="Details" asp-route-id="@item.BHTeamId">Manage Team Roster</a>
                </td>
                <td style="color:white">
                    <a asp-action="Edit" asp-route-id="@item.BHTeamId">Edit</a> |
                    <a asp-action="Delete" asp-route-id="@item.BHTeamId">Delete</a>
                </td>

            }
        </tr>
        }
    </tbody>
</table>

BallHogs/BallHogs/Views/BHTeams/SelectATeam.cshtml
@model IEnumerable<BallHogs.Models.BHTeam>

@{
    ViewData["Title"] = "Index";
}

<h1>Your BHTeam</h1>
<p>Please Select a Team</p>

<table class="table">
    <thead>
        <tr>
            <th>
                Team Name
            </th>
            <th>
                Manager Name
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.TeamName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ManagerName)
            </td>
            <td>
                <!--Do something similar to the BHTeam Details s00000 the button only appears if List of team <5  --maybe change that detail below ti add player-- add players should go to PlayersOnTeam(Index) allowing search and adding players.... Maybe make a view team that only shows team ouside of detail-->
            </td>
            <td align="left">
                @using (Html.BeginForm("LetsBall", "Home", new { Team = item.BHTeamId, TeamName = item.TeamName, Players = item.Players }))
                {
                    <input class="button" type="submit" value="Select Team"/>
                }
            </td>
        </tr>
        }
    </tbody>
</table>